spring:
  datasource:
    url: jdbc:postgresql://ep-rapid-sea-ad4pirrg-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_T0whsOpagFJ9
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  sql:
    init:
      mode: never   # desabilita para depurar
  h2:
    console:
      enabled: false
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      bcopstein: DEBUG
application:
  name: ipitsa
server:
  port: 8080